"""Generate ORD reference pages from the Schema CSVs (single source of truth).

The ORD standard is defined by the CSV files in ``Schema/`` at the repo root
(``ORD_Tables.csv`` and ``ORD_List_of_Fields.csv``). Rather than hand-maintain
reference tables in Markdown, this extension reads those CSVs at build time and
writes MyST Markdown into ``reference/_generated/`` which the reference pages
include. Edit the CSVs, not the generated Markdown.

Runs on the Sphinx ``config-inited`` event, and is also importable/runnable
standalone (``python gen_ord_reference.py``) for quick checks.
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
# docs/source/_ext -> repo root is three levels up
REPO_ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir, os.pardir))
SCHEMA_DIR = os.path.join(REPO_ROOT, "Schema")
OUT_DIR = os.path.join(HERE, os.pardir, "reference", "_generated")


def _read_table(csv_path):
    """Read an ORD Schema CSV, returning (header, rows).

    These CSVs carry a title/legend preamble before the real header; the header
    is the first row whose first cell is ``Category``. Blank rows are dropped.
    """
    with open(csv_path, encoding="utf-8-sig") as fh:
        rows = list(csv.reader(fh))
    header_idx = next(i for i, r in enumerate(rows) if r and r[0].strip() == "Category")
    header = [c.strip() for c in rows[header_idx]]
    data = []
    for r in rows[header_idx + 1:]:
        if not any(c.strip() for c in r):
            continue
        # pad/truncate to header width
        r = (r + [""] * len(header))[:len(header)]
        data.append([c.strip() for c in r])
    return header, data


def _cell(text):
    """Make a value safe for a MyST pipe-table cell."""
    return text.replace("|", "\\|").replace("\n", " ").replace("\r", " ").strip()


def _pipe_table(columns, rows):
    """Render a Markdown pipe table from column headers + row dicts/lists."""
    out = ["| " + " | ".join(columns) + " |",
           "| " + " | ".join(["---"] * len(columns)) + " |"]
    for row in rows:
        out.append("| " + " | ".join(_cell(c) for c in row) + " |")
    return "\n".join(out)


def _write(name, text):
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8") as fh:
        fh.write(text + "\n")


def generate_tables():
    """ORD_Tables.csv -> tables catalogue, grouped by Category."""
    header, data = _read_table(os.path.join(SCHEMA_DIR, "ORD_Tables.csv"))
    col = {h: i for i, h in enumerate(header)}
    cats = {}
    for r in data:
        cats.setdefault(r[col["Category"]], []).append(r)
    parts = ["<!-- generated by _ext/gen_ord_reference.py from Schema/ORD_Tables.csv -->"]
    for cat, rows in cats.items():
        parts.append(f"\n## {cat}\n")
        table_rows = [[r[col["Acroymn"]], r[col["Table"]], r[col["Description"]],
                       r[col.get("Currently in Oasis", -1)] if "Currently in Oasis" in col else ""]
                      for r in rows]
        parts.append(_pipe_table(["Acronym", "Table", "Description", "In Oasis"], table_rows))
    _write("ord_tables.md", "\n".join(parts))
    return len(data)


def generate_fields():
    """ORD_List_of_Fields.csv -> field reference, grouped by Category."""
    header, data = _read_table(os.path.join(SCHEMA_DIR, "ORD_List_of_Fields.csv"))
    col = {h: i for i, h in enumerate(header)}
    cats = {}
    for r in data:
        cats.setdefault(r[col["Category"]], []).append(r)
    parts = ["<!-- generated by _ext/gen_ord_reference.py from Schema/ORD_List_of_Fields.csv -->"]
    for cat, rows in cats.items():
        parts.append(f"\n## {cat}\n")
        table_rows = [[r[col["Proposed Field Name"]], r[col["Table/File"]],
                       r[col["File Format"]], r[col.get("Current Field Name", -1)],
                       r[col["Field Name Description"]]] for r in rows]
        parts.append(_pipe_table(
            ["Field", "Tables / File", "Format", "Current Oasis name", "Description"],
            table_rows))
    _write("ord_fields.md", "\n".join(parts))
    return len(data)


def run(app=None, config=None):
    n_tables = generate_tables()
    n_fields = generate_fields()
    msg = f"[gen_ord_reference] wrote {n_tables} tables, {n_fields} fields -> reference/_generated/"
    if app is not None:
        from sphinx.util import logging
        logging.getLogger(__name__).info(msg)
    else:
        print(msg)


def setup(app):
    app.connect("config-inited", run)
    return {"parallel_read_safe": True, "parallel_write_safe": True}


if __name__ == "__main__":
    run()
